- hosts: all
  become: true
  tasks:
    - name: Install Apache
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: true

    - name: Copy index.html to Apache directory
      copy:
        src: /vagrant/index.html
        dest: /var/www/html/index.html